import Head from 'next/head';
import ContactCom from './../../components/App/Contact';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Tec in every home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ContactCom />
    </div>
  )
}