import Head from 'next/head';
import Image from 'next/image';
import SchoolCom from './../../components/App/School';


export default function Home() {
  return (
    <div>
      <Head>
        <title>Tec in every home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SchoolCom />
    </div>
  )
}