import Head from 'next/head';
import Image from 'next/image';
import CommunityCom from './../../components/App/Community';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Tec in every home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CommunityCom />
    </div>
  )
}